#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test check_meta_undocumented_test correctly identifies
#'   real test_that calls via AST parsing and ignores test_that appearing
#'   inside string literals.
test_that("CheckMetaUndocumentedTest", {
  # Documented test_that is not flagged ----
  documented <- tempfile(fileext = ".R")
  writeLines(c(
    "#' @meta author Test",
    "#' @meta reviewer Test",
    "#' @meta review_date 2024-01-01",
    "#' @meta description A test.",
    "test_that(\"MyTest\", {",
    "  expect_true(TRUE)",
    "})"
  ), documented)
  result <- suppressMessages(check_meta_undocumented_test(files_test = documented, concise = TRUE))
  expect_length(result, 0)

  # Undocumented test_that is flagged ----
  undocumented <- tempfile(fileext = ".R")
  writeLines(c(
    "test_that(\"NoDoc\", {",
    "  expect_true(TRUE)",
    "})"
  ), undocumented)
  result <- suppressMessages(check_meta_undocumented_test(files_test = undocumented, concise = TRUE))
  expect_length(result, 1)
  expect_equal(result[[1]], 1L)

  # test_that inside string literal is not flagged ----
  string_literal <- tempfile(fileext = ".R")
  writeLines(c(
    "#' @meta author Test",
    "#' @meta reviewer Test",
    "#' @meta review_date 2024-01-01",
    "#' @meta description A test with embedded test_that in string.",
    "test_that(\"StringLiteral\", {",
    "  code <- \"",
    "  test_that('inner', {",
    "    expect_true(TRUE)",
    "  })",
    "  \"",
    "  expect_true(TRUE)",
    "})"
  ), string_literal)
  result <- suppressMessages(check_meta_undocumented_test(files_test = string_literal, concise = TRUE))
  expect_length(result, 0)

  # Clean up ----
  unlink(c(documented, undocumented, string_literal))
})

#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test check_meta_rd detects missing meta tags in Rd files,
#'   excludes package-level Rd files, and stops with print_error.
test_that("CheckMetaRd", {
  # Helper to create Rd files ----
  make_rd <- function(name, meta_block = NULL, package_rd = FALSE) {
    f <- tempfile(fileext = ".Rd")
    lines <- c(
      "% Generated by roxygen2: do not edit by hand",
      paste0("\\name{", name, "}"),
      paste0("\\title{", name, "}")
    )
    if (package_rd) {
      lines <- c(lines, "\\docType{package}")
    }
    if (!is.null(meta_block)) {
      lines <- c(lines, meta_block)
    }
    writeLines(lines, f)
    f
  }

  complete_meta <- c(
    "\\meta{",
    "Id: URS01.FS001",
    "",
    "Compliance Risk: low",
    "",
    "Implementation Complexity: low",
    "",
    "Test Scope: low",
    "}"
  )

  # All tags present ----
  rd_complete <- make_rd("my_func", complete_meta)
  result <- suppressMessages(check_meta_rd(files_rd = rd_complete, concise = TRUE))
  expect_equal(nrow(result), 0)

  # Missing tags detected ----
  rd_missing <- make_rd("my_func")
  result <- suppressMessages(check_meta_rd(files_rd = rd_missing, concise = TRUE))
  expect_true(nrow(result) > 0)

  # Package Rd excluded by default ----
  rd_pkg_dir <- tempdir()
  rd_pkg <- file.path(rd_pkg_dir, "mypkg-package.Rd")
  make_rd_to <- function(path, name, meta_block = NULL, package_rd = FALSE) {
    lines <- c(
      "% Generated by roxygen2: do not edit by hand",
      paste0("\\name{", name, "}"),
      paste0("\\title{", name, "}")
    )
    if (package_rd) lines <- c(lines, "\\docType{package}")
    if (!is.null(meta_block)) lines <- c(lines, meta_block)
    writeLines(lines, path)
    path
  }
  make_rd_to(rd_pkg, "mypkg-package", package_rd = TRUE)
  result <- suppressMessages(check_meta_rd(files_rd = c(rd_complete, rd_pkg), concise = TRUE))
  expect_equal(nrow(result), 0)

  # print_error stops on missing tags ----
  expect_error(suppressMessages(
    check_meta_rd(files_rd = rd_missing, concise = TRUE, print_error = TRUE)
  ), "missing required meta tags")

  # Custom Rd tags validated when specified ----
  rd_custom <- make_rd("custom_func", c(
    "\\meta{",
    "Id: FS001",
    "",
    "Compliance Risk: low",
    "",
    "Implementation Complexity: low",
    "",
    "Test Scope: low",
    "",
    "Owner: Team Alpha",
    "}"
  ))
  result <- suppressMessages(check_meta_rd(
    files_rd = rd_custom,
    check_rd_tag_exist = c("Id", "Compliance Risk", "Owner"),
    concise = TRUE
  ))
  expect_equal(nrow(result), 0)

  # Missing custom Rd tag detected ----
  result <- suppressMessages(check_meta_rd(
    files_rd = rd_complete,
    check_rd_tag_exist = c("Id", "Owner"),
    concise = TRUE
  ))
  expect_true(nrow(result) > 0)

  # Clean up ----
  unlink(c(rd_complete, rd_missing, rd_pkg, rd_custom))
})

#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test check_meta_test detects missing meta tags in test
#'   file roxygen blocks and stops with print_error.
test_that("CheckMetaTest", {
  # Helper to create test files ----
  make_test <- function(meta_lines, test_name = "MyTest") {
    f <- tempfile(fileext = ".R")
    writeLines(c(
      meta_lines,
      paste0("test_that(\"", test_name, "\", {"),
      "  expect_true(TRUE)",
      "})"
    ), f)
    f
  }

  # All tags present ----
  complete <- make_test(c(
    "#' @meta author Alice",
    "#' @meta reviewer Bob",
    "#' @meta review_date 2024-01-01",
    "#' @meta description A complete test."
  ))
  result <- suppressMessages(check_meta_test(files_test = complete, concise = TRUE))
  expect_length(result, 0)

  # Missing tags detected ----
  incomplete <- make_test(c(
    "#' @meta author Alice"
  ))
  result <- suppressMessages(check_meta_test(files_test = incomplete, concise = TRUE))
  expect_length(result, 1)

  # print_error stops on missing tags ----
  expect_error(suppressMessages(
    check_meta_test(files_test = incomplete, concise = TRUE, print_error = TRUE)
  ), "missing meta tags")

  # Custom tags validated when specified ----
  with_custom <- make_test(c(
    "#' @meta author Alice",
    "#' @meta reviewer Bob",
    "#' @meta review_date 2024-01-01",
    "#' @meta description A test.",
    "#' @meta jira_ticket PROJ-123"
  ))
  result <- suppressMessages(check_meta_test(
    files_test = with_custom,
    check_test_tag_exist = c("author", "reviewer", "review_date", "description", "jira_ticket"),
    concise = TRUE
  ))
  expect_length(result, 0)

  # Missing custom tag detected ----
  result <- suppressMessages(check_meta_test(
    files_test = with_custom,
    check_test_tag_exist = c("author", "reviewer", "review_date", "description", "sprint"),
    concise = TRUE
  ))
  expect_length(result, 1)

  # Clean up ----
  unlink(c(complete, incomplete, with_custom))
})

#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test check_meta_unique_ids detects duplicate IDs across
#'   Rd files and stops with print_error.
test_that("CheckMetaUniqueIds", {
  # Helper to create Rd files with meta ----
  make_rd <- function(name, id) {
    f <- tempfile(fileext = ".Rd")
    writeLines(c(
      "% Generated by roxygen2: do not edit by hand",
      paste0("\\name{", name, "}"),
      paste0("\\title{", name, "}"),
      "\\meta{",
      paste0("Id: ", id),
      "",
      "Compliance Risk: low",
      "",
      "Implementation Complexity: low",
      "",
      "Test Scope: low",
      "}"
    ), f)
    f
  }

  # Unique IDs pass ----
  rd1 <- make_rd("func_a", "FS001")
  rd2 <- make_rd("func_b", "FS002")
  result <- suppressMessages(check_meta_unique_ids(files_rd = c(rd1, rd2), concise = TRUE))
  expect_equal(nrow(result), 0)

  # Duplicate IDs detected ----
  rd3 <- make_rd("func_c", "FS001")
  result <- suppressMessages(check_meta_unique_ids(files_rd = c(rd1, rd3), concise = TRUE))
  expect_true(nrow(result) > 0)

  # print_error stops on duplicates ----
  expect_error(suppressMessages(
    check_meta_unique_ids(
      files_rd = c(rd1, rd3), concise = TRUE, print_error = TRUE
    )
  ), "duplicated")

  # Clean up ----
  unlink(c(rd1, rd2, rd3))
})

#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test check_meta orchestrator runs all sub-checks and
#'   aggregates errors with print_error.
test_that("CheckMetaOrchestrator", {
  # All checks pass ----
  rd_file <- tempfile(fileext = ".Rd")
  writeLines(c(
    "% Generated by roxygen2: do not edit by hand",
    "\\name{my_func}",
    "\\title{my_func}",
    "\\meta{",
    "Id: URS01.FS001",
    "",
    "Compliance Risk: low",
    "",
    "Implementation Complexity: low",
    "",
    "Test Scope: low",
    "}"
  ), rd_file)

  test_file <- tempfile(fileext = ".R")
  writeLines(c(
    "#' @meta author Alice",
    "#' @meta reviewer Bob",
    "#' @meta review_date 2024-01-01",
    "#' @meta description A test.",
    "test_that(\"MyTest\", {",
    "  expect_true(TRUE)",
    "})"
  ), test_file)

  result <- suppressMessages(check_meta(
    files_rd = rd_file, files_test = test_file, concise = TRUE
  ))
  expect_true(all(sapply(result, function(x) length(x) == 0 || NROW(x) == 0)))

  # Failing checks with print_error ----
  rd_bad <- tempfile(fileext = ".Rd")
  writeLines(c(
    "% Generated by roxygen2: do not edit by hand",
    "\\name{bad_func}",
    "\\title{bad_func}"
  ), rd_bad)

  expect_error(suppressMessages(
    check_meta(
      files_rd = rd_bad, files_test = test_file,
      concise = TRUE, print_error = TRUE
    )
  ), "One or more errors")

  # Clean up ----
  unlink(c(rd_file, test_file, rd_bad))
})
