#' @meta author Moritz Lang
#' @meta reviewer Mario Annau
#' @meta review_date 2026-05-22
#' @meta description Test parse_rd_meta extracts meta tags from Rd files into
#'   a data.frame, handles missing meta sections, and processes multiple files.
test_that("ParseRdMeta", {
  # Helper to create Rd files ----
  make_rd <- function(name, meta_block = NULL) {
    f <- tempfile(fileext = ".Rd")
    lines <- c(
      "% Generated by roxygen2: do not edit by hand",
      paste0("\\name{", name, "}"),
      paste0("\\title{", name, "}")
    )
    if (!is.null(meta_block)) lines <- c(lines, meta_block)
    writeLines(lines, f)
    f
  }

  # Rd with meta section ----
  rd_with <- make_rd("my_func", c(
    "\\meta{",
    "Id: URS01.FS001",
    "",
    "Compliance Risk: low",
    "",
    "Implementation Complexity: medium",
    "",
    "Test Scope: high",
    "}"
  ))
  result <- parse_rd_meta(rd_with)
  expect_equal(nrow(result), 1)
  expect_equal(result$Id, "URS01.FS001")
  expect_equal(result$`Compliance Risk`, "low")
  expect_equal(result$`Implementation Complexity`, "medium")
  expect_equal(result$`Test Scope`, "high")

  # Rd without meta section ----
  rd_without <- make_rd("bare_func")
  result <- parse_rd_meta(rd_without)
  expect_equal(nrow(result), 1)
  expect_equal(ncol(result), 1)
  expect_equal(names(result), "filepath")

  # Multiple files ----
  rd_second <- make_rd("other_func", c(
    "\\meta{",
    "Id: URS01.FS002",
    "",
    "Compliance Risk: high",
    "}"
  ))
  result <- parse_rd_meta(c(rd_with, rd_second))
  expect_equal(nrow(result), 2)
  expect_equal(result$Id, c("URS01.FS001", "URS01.FS002"))

  # Clean up ----
  unlink(c(rd_with, rd_without, rd_second))
})
